version: '3.9'

services:

  postgresDB:
    image: postgres
    container_name: postgres_container
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: pnopjira
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 65420071@kmitl.ac.th
      PGADMIN_DEFAULT_PASSWORD: Kmitl#71
    ports:
      - 5050:80
    networks:
      - internal

volumes:
  postgres-data:

networks:
  internal:
