# version: '3.8'
services:

  postgresDB:
    image: postgres
    container_name: postgres_container
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: pnopjira
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    volumes:
      - ./scripts:/scripts
      - ./subject:/data/subject
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - internal
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 65420071@kmitl.ac.th
      PGADMIN_DEFAULT_PASSWORD: Kmitl#71
    ports:
      - 5050:80
    networks:
      - internal

  jupyter:
    build: .
    ports:
      - "8888:8888"
    networks:
      - internal
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=8b3a6b5a9d9b2c9e3c12d7e1a2f5b8a7f9d4e1c3b2a9f0e3d6c5b7a8c3e9d2f0
    # command: start-notebook.sh

volumes:
  scripts:
  subject:
  postgres-data:
  notebook:

networks:
  internal:
